[theme]
primaryColor = "#d71e28"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#1F2937"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"
showSidebarNavigation = false

[server]
port = 8501
headless = true
runOnSave = true

[logger]
level = "info"



